### ISSUE TITLE
comment_saved and call_end_ringtone event are not triggering at the demo page.

### ISSUE THREAD

**Issue by williamlimianto** [aircall/aircall-everywhere#27]
So I found the Aircall Everywhere SDK from Aircall API Documentation then I went to the demo page to check them.

However, I found that the comment_saved and call_end_ringtone event are not triggering during / after the outbound call.

Can anyone check this issue? Thanks!

**Comment by eulbat** [comment]
Hi @williamlimianto 
Thank you for the report, we'll look into it

**Comment by williamlimianto** [comment]
Hi @eulbat ,
Is there any update regarding this case?

I just want to make sure because the Aircall Support team already set the ticket to "Resolved as Known Issue" due to the issue is handled here (Github) and not at the Aircall Support portal.

Thanks!
![Screenshot_4](https://user-images.githubusercontent.com/7065829/95969878-7a237180-0e39-11eb-90d8-bca6cacdb612.jpg)

**Comment by eulbat** [comment]
Hello @williamlimianto 

This is still in progress on our side.
I will update this issue when a fix is ready.

**Comment by eulbat** [comment]
Hello @williamlimianto 

We have fixed the issue on the `comment_saved` event not being sent.
The `call_end_ringtone`, however, is working as expected. It is only sent for incoming calls, I will update the documentation to reflect that. Sorry about the confusion.

Closing this ticket now, feel free to reopen if you have more information
