### ISSUE TITLE
incoming_call doesn't appear to be firing

### ISSUE THREAD

**Issue by rideau-nostalgia** [aircall/aircall-everywhere#32]
Just trying to get aircall-everywhere integrated with our app and have been unable to get the 'incoming_call' event to fire. When running in debug mode this doesn't appear to even produce an event in the way other events do. 

Even the Aircall Everywhere demo page seems to have this issue as well - no event ever appears in the events section of the page, and if the phone is collapsed, it never auto-reappears as the demo event listener calls for.

Is this something I'm doing wrong, or a known issue with the client?

**Comment by rideau-nostalgia** [comment]
After a bit more investigating I was able to determine that external inbound calls due result in the event being fired, but both internal calls, and external calls that are transferred to a user do not result in the event being fired. As a result, we're not able to make the phone client visible while it's ringing with these types of calls (which is a fairly significant impediment to useability in our case). Is there any known solution to this at present?

**Comment by eulbat** [comment]
Hello @rideau-nostalgia 
Thanks for reporting this. We'll investigate and come back to you.

**Comment by eulbat** [comment]
Hello @rideau-nostalgia 
The issue should be fixed

Please feel free to reopen this issue if the problem persists

**Comment by rideau-nostalgia** [comment]
Hey @eulbat. Same issue still seems to be happening. If I am a user on an aircall number that directly receives a call from an external number, it does result in the "incoming_call" event firing, but receiving an internal call (or a transfer) from another aircall user still doesn't fire this event. 

We can see this behaviour not only in our own app, but also when logged in on the Aircall Everywhere demo page (https://aircall.github.io/aircall-everywhere/). Monitoring the "call lifecycle events" area will not result in an "incoming_call" event for an internal call from another user or a transfer.

I'd be happy to demo this for someone if that'd help?

**Comment by eulbat** [comment]
Hey @rideau-nostalgia 
Just ran another test, the `incoming_call` are correctly showing up when receiving transfers (both warm and cold transfers).
The event is indeed not sent when receiving an internal call. This is however expected and we will update our documentation accordingly.
