### ISSUE TITLE
How to auto login into aircall phone window after the authentication with aircall account (Oauth)?

### ISSUE THREAD

**Issue by kamleshProtech** [aircall/aircall-everywhere#35]
How to auto-login into aircall phone window after the authentication with aircall account (Oauth)?

In our app, firstly authenticate the aircall account (using Oauth integration) and after the authentication process, aircall redirects to our website/app and on this redirect page, we display aircall phone window, but the aircall phone is not auto-login first time. We again login into this window.

Can you provide a solution for this so we can use a single login?

**Comment by eulbat** [comment]
Hello @kamleshProtech 

This is expected, the OAuth flow is to authorise your integration to use the public API, but it does not affect the user being logged into the phone or not.
The user will have to log into the embedded phone, unless they were already logged in the web app.
