### ISSUE TITLE
Reload page 

### ISSUE THREAD

**Issue by johnn-elabogado** [aircall/aircall-everywhere#36]
We have integrated the phone and sometime the page is refreshed auto, we haven't idea why.

could be that this happen for an event with the phone ? 

this is a problem serious for us because this happens while our agents are in a call, so the call finish.

**Comment by eulbat** [comment]
Hello @johnn-elabogado 

aircall-everywhere does not refresh the page.

Your issue must be coming from somewhere else.

I'm closing the ticket, feel free to reopen if you have more information
