### ISSUE TITLE
Can not use in production

### ISSUE THREAD

**Issue by pieeee** [aircall/aircall-everywhere#91]
Though the SDK works in local environment, when we push it to production,
```Refused to frame 'https://phone.aircall.io/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' http://localhost:* *.fusionamspro.com *.inzee.care *.fusionsd.com.au *.clevero.co *.driver360.org *.thescouts.com.au *.ubbitt.com ubbitt.com *.boxtal.com support.upowr.com crm.core.upowr.cloud enforceau.com.au *.avicrm.net *.aviseguros.com freshsales.io api.freshsales.io events.freshsales.io cdn.freshsales.io app.freshsales.io accounts.freshsales.io dnalegalmim.com *.dnalegalmim.com homepro.com *.homepro.com *.getheroes.run *.crisp.chat app.zeliq.com zeliq.com app.eambulanta.si *.peppercloud.com *.mypropertysuite.io ucrmweb.co integration.ucrmweb.co cedf.my.site.com *.leovida.com *.vivaservices.fr *.menageo.fr *.vipmanaging.com *.desibites.com *.odoo.com *.edesk.com *.90tech.fr *.scaffold.digital *.dnalegalmim.com openinfrase.my.site.com *.onlive.site *.avicrm.es crm.foodforjoe.es *.abuelosplus.es *.retraiteplus.ch *.seniorhomeplus.uk *.casas-senior.pt *.placessenior.com *.casadiriposopiu.it *.uniresi.es app.frontapp.com *.kalendes.com bolt.buscoresi.com *.aurasoft.fr *.cloudfront.net *.aircall.io bolt.buscoresi.com *.alan.com alan.com yonivers.aurasoft.fr aurasoft.fr *.freshdesk.com *.myfreshworks.com *.myfreshworks.dev *.freshpo.com *.freshpori.com *.freshchat.com *.juno.legal *.juno.works aircall.github.io *.freshworks.com *.tangerineglobal.com *.microsoft.com *.novatedleaseaustralia.com.au *.formaliteauto.com *.retraiteplus.be *.nocrm.io *.avaibook.com *.amazonaws.com *.anwalt.de *.apollo.io *.bloobirds.com *.casinobarcelona.es *.flatfair.co.uk *.doctoralia.es *.doktortakvimi.com *.clivi.com.mx *.documentforce.com *.drivania.com *.elabogado.com *.feit.com *.firstluggage.com *.foodsby.com *.futuresimple.com *.geomapper.io *.gibobs.com *.golftec.com *.google.com *.greenpan.com *.happyfox.com *.heymarket.com *.homevest.io *.hopkins.systems *.hubspoteditor.com *.hubspot.com *.inspiringvacations.com *.intercom.com *.jameda.de *.jumpcloud.com *.kactus.com *.lemlist.com *.linear.app *.linkedin.com *.looker.com *.lussostone.com *.live.com *.macartevacances.fr *.medicalcard.io *.missiveapp.com *.niceincontact.com *.office.net *.okta-emea.com *.okta.com *.outreach.io *.prenuvo.com *.reamaze.com *.rebag.com *.rezdy.com *.simplebo.net *.shopware.com *.soldo.com *.sortlist.com *.sportscope.com *.steeple.fr *.theguarantors.com *.treble.ai *.zehnder.fr *.zendesk.com *.zendesk.es *.adyen.help *.asana.com *.blablacar.com *.callexcell.be *.com.slack *.deporvillage.com *.doctoranytime.gr *.lusha.com *.medelse.com *.merxu.com *.onepilot.co *.planhat.com *.poppy.be *.retraiteplus.fr *.stikets.info *.swipoo.com *.tailorbrands.com *.tiierisch.de *.zdusercontent.com *.visualforce.com *.salesforce-experience.com *.salesforce.com *.force.com *.doctoralia.com.br *.doctoralia.es *.hapily.com *.myrightmove.com.au *.mobilemod.com mobilemod.com *.docs.google.com *.derecho.com *.csp.withgoogle.com *.ssl.gstatic.com *.apis.google.com *.script.google.com *.googleusercontent.com *.bubble.io bubble.io *.frontapp.com *.freshdev.io https://fairsquaremedicare.com/ *.app.bedrockmedicare.com".```

Any idea to fix this?

**Comment by francofrati** [comment]
I have the same issue. It was working fine until a few months ago and now only works in local/dev environment.
The project uses vite+react+ts .
Any solution?

**Comment by pieeee** [comment]
Hi @francofrati , You need to contact the support team to whitelist your domain.
